#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#mpd &			# music player daemon-you might prefer it as a service though
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
#dunst &		# dunst for notifications
xset r rate 350 60 &	# Speed xrate up
xrandr --output HDMI1 --auto --scale 1.0x1.0 && xrandr --output eDP1 --off &   # disabling eDP1 if HDMI1 connected
#unclutter &		# Remove mouse when idle
#echo '4000' > /sys/class/backlight/intel_backlight/brightness &
